spring.application.name=webmusic-api
spring.data.mongodb.uri=mongodb://localhost:27017/webmusic-database
spring.data.mongodb.database=webmusic-database

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB


gemini.api.key=AIzaSyDJjnHaGFG1_JaI5qzh9dzJF7Qho0WVZYQ
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent

